version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/go/src/github.com/selfManager
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 55432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
