version: '3.8'
services:
  app:
    container_name: "self_manager_app"
    build:
      context: .
      dockerfile: build/Dockerfile
      target: dev
    env_file:
      - build/.env.dev
    ports:
      - 80:80
    volumes:
      - .:/go/src
    depends_on:
        db:
          condition: service_healthy
  db:
    image: postgres:14.1-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - build/.env.dev
    ports:
      - 55432:5432
    volumes:
      - ./build/postgres:/docker-entrypoint-initdb.d
  testdb:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - build/.env.test
    ports:
      - 55433:5432
