version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - .:/go/src/github.com/selfManager
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env.dev
    ports:
      - 55432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  testdb:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env.test
    ports:
      - 55433:5432
    volumes:
      - ./postgres_data/test_data:/var/lib/postgresql/data
